### ISSUE TITLE
Nextion Display + Nextiondriver shows wrong Date Format

### ISSUE THREAD

**Issue by feedzapper** [BrandMeister/DisplayServer#1]
I use the AG4OJ Nextion Display-Code with his modfied Nextiondriver and DMRHost
The Date will always shown as 02/27/21.
If i switch to MMDVMHost, all works fine. The Date will shown as 27.02.21 in the Display (nothing changed in the settings)
locale here :
LC_TIME="de_DE.UTF-8"

**Comment by stefansaraev** [comment]
We build our static binaries published in our debian repo against musl libc. musl's locale support is limited, so if you need LC_TIME working on your system, I'd suggest that you compile DisplayServer from source instead of using our pre-compiled binaries.

**Comment by feedzapper** [comment]
Thanks for the Info.
I will try this and compile it direct from the source...
